### ISSUE TITLE
Release this component and an unmanaged package

### ISSUE THREAD

**Issue by Garywoo** [foxysolutions/LWC-RecordtType-PicklistValue-Selector#4]
Please can I request that you release this component as an unmanaged package, so it can be quickly installed in a Salesforce org?

I do not know how to deploy a component such as this manually.

Thanks 😁

**Comment by keytactic** [comment]
Agreed. That would be wonderful.

**Comment by Garywoo** [comment]
@keytactic, I found this tool which lets you deploy directly from Github. I used it to deploy this component easily. 

http://githubsfdeploy.herokuapp.com/app/githubdeploy/foxysolutions/LWC-RecordtType-PicklistValue-Selector

**Comment by foxysolutions** [comment]
There are pros and cons on releasing this as an umanaged package. Easiest would be to use a tool like Gary provided above. In case several others still would be benefitting from this component to be released as unmanaged package, please let me know.

**Comment by keytactic** [comment]
> @keytactic, I found this tool which lets you deploy directly from Github. I used it to deploy this component easily. 
> 
> http://githubsfdeploy.herokuapp.com/app/githubdeploy/foxysolutions/LWC-RecordtType-PicklistValue-Selector

Thank you!

@foxysolutions thank you for following up. Much appreciated.
