### ISSUE TITLE
Record Type Permissions to Run Flow Requires App Permissions/Manage record types and layouts for Files

### ISSUE THREAD

**Issue by soniaDis** [foxysolutions/LWC-RecordtType-PicklistValue-Selector#5]
Hello,
Fantastic component and exactly what I was looking for!  After moving into production however, the component fails for some of my users who do not have Manage record types and layouts for Files assigned in the App Permissions. 
 This is problematic for me since as a result of dependent permissions, the user would now need View Setup and Configuration and Customized Application.  These users can not have this level of access but need to be able to add a record to an object that is Record Type dependent.  Any suggestions on a fix?

Thank you!

**Comment by foxysolutions** [comment]
@soniaDis apologies for the extremely late reply. I am however very curious whether this issue still occurs, as this component utilises the standard RecordType selection behaviour as Salesforce uses in their UI. By definition the user should not require any permission to select a Recordtype he/she has access to via standard Profile assignments. Might this have been within the logic upfront where you gather the RecordTypeId?

Again, apologies for late reply and hope you found a solution, or else, happy to help.

**Comment by foxysolutions** [comment]
Closed this issue as no information was provided for more than 6 months.
